version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: asktennis_local_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: asktennis_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: asktennis_local_app
    depends_on:
      - db
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/asktennis_local?sslmode=disable
      GROQ_API_KEY: ${GROQ_API_KEY}
      SPORTRADAR_API_KEY: ${SPORTRADAR_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    command: ["node", "server.js"]


volumes:
  postgres_data:
